version: '3.9'

services:

  nestjs:
    build:
      context: .
    container_name: nestjs
    restart: unless-stopped
    environment:
      - POSTGRES_USER=local-db
      - POSTGRES_PASSWORD=local-db
      - POSTGRES_HOST=local-db
      - POSTGRES_DB=local-db
      - POSTGRES_PORT=5432
      - NODE_ENV=development
    volumes:
      - ./:/usr/app
    ports:
      - 3000:3000

  local-db:
    container_name: local-db
    restart: unless-stopped
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_USER=local-db
      - POSTGRES_PASSWORD=local-db
      - POSTGRES_DB=local-db

  adminer:
    image: adminer:4.8.1-standalone
    ports: 
      - 8080:8080
